update=10/8/2016 7:27:23 PM
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[eeschema]
version=1
LibDir=
[eeschema/libraries]
LibName1=K:/Projects/satnogs/satnogs-rotator-controller/PCB/library/satnogs
LibName2=C:/Program Files/KiCad/share/kicad/library/74xgxx
LibName3=C:/Program Files/KiCad/share/kicad/library/74xx
LibName4=C:/Program Files/KiCad/share/kicad/library/ac-dc
LibName5=C:/Program Files/KiCad/share/kicad/library/actel
LibName6=C:/Program Files/KiCad/share/kicad/library/adc-dac
LibName7=C:/Program Files/KiCad/share/kicad/library/Altera
LibName8=C:/Program Files/KiCad/share/kicad/library/analog_devices
LibName9=C:/Program Files/KiCad/share/kicad/library/analog_switches
LibName10=C:/Program Files/KiCad/share/kicad/library/atmel
LibName11=C:/Program Files/KiCad/share/kicad/library/audio
LibName12=C:/Program Files/KiCad/share/kicad/library/brooktre
LibName13=C:/Program Files/KiCad/share/kicad/library/cmos_ieee
LibName14=C:/Program Files/KiCad/share/kicad/library/cmos4000
LibName15=C:/Program Files/KiCad/share/kicad/library/conn
LibName16=C:/Program Files/KiCad/share/kicad/library/contrib
LibName17=C:/Program Files/KiCad/share/kicad/library/cypress
LibName18=C:/Program Files/KiCad/share/kicad/library/dc-dc
LibName19=C:/Program Files/KiCad/share/kicad/library/device
LibName20=C:/Program Files/KiCad/share/kicad/library/digital-audio
LibName21=C:/Program Files/KiCad/share/kicad/library/diode
LibName22=C:/Program Files/KiCad/share/kicad/library/display
LibName23=C:/Program Files/KiCad/share/kicad/library/dsp
LibName24=C:/Program Files/KiCad/share/kicad/library/elec-unifil
LibName25=C:/Program Files/KiCad/share/kicad/library/ESD_Protection
LibName26=C:/Program Files/KiCad/share/kicad/library/ftdi
LibName27=C:/Program Files/KiCad/share/kicad/library/gennum
LibName28=C:/Program Files/KiCad/share/kicad/library/graphic
LibName29=C:/Program Files/KiCad/share/kicad/library/hc11
LibName30=C:/Program Files/KiCad/share/kicad/library/intel
LibName31=C:/Program Files/KiCad/share/kicad/library/interface
LibName32=C:/Program Files/KiCad/share/kicad/library/ir
LibName33=C:/Program Files/KiCad/share/kicad/library/Lattice
LibName34=C:/Program Files/KiCad/share/kicad/library/linear
LibName35=C:/Program Files/KiCad/share/kicad/library/logo
LibName36=C:/Program Files/KiCad/share/kicad/library/maxim
LibName37=C:/Program Files/KiCad/share/kicad/library/memory
LibName38=C:/Program Files/KiCad/share/kicad/library/microchip
LibName39=C:/Program Files/KiCad/share/kicad/library/microchip_dspic33dsc
LibName40=C:/Program Files/KiCad/share/kicad/library/microchip_pic10mcu
LibName41=C:/Program Files/KiCad/share/kicad/library/microchip_pic12mcu
LibName42=C:/Program Files/KiCad/share/kicad/library/microchip_pic16mcu
LibName43=C:/Program Files/KiCad/share/kicad/library/microchip_pic18mcu
LibName44=C:/Program Files/KiCad/share/kicad/library/microchip_pic32mcu
LibName45=C:/Program Files/KiCad/share/kicad/library/microcontrollers
LibName46=C:/Program Files/KiCad/share/kicad/library/motor_drivers
LibName47=C:/Program Files/KiCad/share/kicad/library/motorola
LibName48=C:/Program Files/KiCad/share/kicad/library/msp430
LibName49=C:/Program Files/KiCad/share/kicad/library/nordicsemi
LibName50=C:/Program Files/KiCad/share/kicad/library/nxp_armmcu
LibName51=C:/Program Files/KiCad/share/kicad/library/onsemi
LibName52=C:/Program Files/KiCad/share/kicad/library/opto
LibName53=C:/Program Files/KiCad/share/kicad/library/Oscillators
LibName54=C:/Program Files/KiCad/share/kicad/library/philips
LibName55=C:/Program Files/KiCad/share/kicad/library/power
LibName56=C:/Program Files/KiCad/share/kicad/library/Power_Management
LibName57=C:/Program Files/KiCad/share/kicad/library/powerint
LibName58=C:/Program Files/KiCad/share/kicad/library/pspice
LibName59=C:/Program Files/KiCad/share/kicad/library/references
LibName60=C:/Program Files/KiCad/share/kicad/library/regul
LibName61=C:/Program Files/KiCad/share/kicad/library/relays
LibName62=C:/Program Files/KiCad/share/kicad/library/rfcom
LibName63=C:/Program Files/KiCad/share/kicad/library/sensors
LibName64=C:/Program Files/KiCad/share/kicad/library/silabs
LibName65=C:/Program Files/KiCad/share/kicad/library/siliconi
LibName66=C:/Program Files/KiCad/share/kicad/library/stm8
LibName67=C:/Program Files/KiCad/share/kicad/library/stm32
LibName68=C:/Program Files/KiCad/share/kicad/library/supertex
LibName69=C:/Program Files/KiCad/share/kicad/library/switches
LibName70=C:/Program Files/KiCad/share/kicad/library/texas
LibName71=C:/Program Files/KiCad/share/kicad/library/transf
LibName72=C:/Program Files/KiCad/share/kicad/library/transistors
LibName73=C:/Program Files/KiCad/share/kicad/library/ttl_ieee
LibName74=C:/Program Files/KiCad/share/kicad/library/valves
LibName75=C:/Program Files/KiCad/share/kicad/library/video
LibName76=C:/Program Files/KiCad/share/kicad/library/Xicor
LibName77=C:/Program Files/KiCad/share/kicad/library/xilinx
LibName78=C:/Program Files/KiCad/share/kicad/library/Zilog
[schematic_editor]
version=1
PageLayoutDescrFile=
PlotDirectoryName=
SubpartIdSeparator=0
SubpartFirstId=65
NetFmtName=
SpiceForceRefPrefix=0
SpiceUseNetNumbers=0
LabSize=60
